/* automatically generated by rust-bindgen */

extern "C" { pub fn levenshtein ( a : * const :: std :: os :: raw :: c_char , b : * const :: std :: os :: raw :: c_char ) -> :: std :: os :: raw :: c_uint ; }